using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FoodDataImport;

public class FoodItemRaw
{
    public long Id { get; set; }
    public string? Code { get; set; }
    public string? Url { get; set; }
    public string? Creator { get; set; }
    public string? CreatedT { get; set; }
    public string? CreatedDatetime { get; set; }
    public string? LastModifiedT { get; set; }
    public string? LastModifiedDatetime { get; set; }
    public string? LastModifiedBy { get; set; }
    public string? LastUpdatedT { get; set; }
    public string? LastUpdatedDatetime { get; set; }
    public string? ProductName { get; set; }
    public string? AbbreviatedProductName { get; set; }
    public string? GenericName { get; set; }
    public string? Quantity { get; set; }
    public string? Packaging { get; set; }
    public string? PackagingTags { get; set; }
    public string? PackagingEn { get; set; }
    public string? PackagingText { get; set; }
    public string? Brands { get; set; }
    public string? BrandsTags { get; set; }
    public string? BrandsEn { get; set; }
    public string? Categories { get; set; }
    public string? CategoriesTags { get; set; }
    public string? CategoriesEn { get; set; }
    public string? Origins { get; set; }
    public string? OriginsTags { get; set; }
    public string? OriginsEn { get; set; }
    public string? ManufacturingPlaces { get; set; }
    public string? ManufacturingPlacesTags { get; set; }
    public string? Labels { get; set; }
    public string? LabelsTags { get; set; }
    public string? LabelsEn { get; set; }
    public string? EmbCodes { get; set; }
    public string? EmbCodesTags { get; set; }
    public string? FirstPackagingCodeGeo { get; set; }
    public string? Cities { get; set; }
    public string? CitiesTags { get; set; }
    public string? PurchasePlaces { get; set; }
    public string? Stores { get; set; }
    public string? Countries { get; set; }
    public string? CountriesTags { get; set; }
    public string? CountriesEn { get; set; }
    public string? IngredientsText { get; set; }
    public string? IngredientsTags { get; set; }
    public string? IngredientsAnalysisTags { get; set; }
    public string? Allergens { get; set; }
    public string? AllergensEn { get; set; }
    public string? Traces { get; set; }
    public string? TracesTags { get; set; }
    public string? TracesEn { get; set; }
    public string? ServingSize { get; set; }
    public string? ServingQuantity { get; set; }
    public string? NoNutritionData { get; set; }
    public string? AdditivesN { get; set; }
    public string? Additives { get; set; }
    public string? AdditivesTags { get; set; }
    public string? AdditivesEn { get; set; }
    public string? NutriscoreScore { get; set; }
    public string? NutriscoreGrade { get; set; }
    public string? NovaGroup { get; set; }
    public string? PnnsGroups1 { get; set; }
    public string? PnnsGroups2 { get; set; }
    public string? FoodGroups { get; set; }
    public string? FoodGroupsTags { get; set; }
    public string? FoodGroupsEn { get; set; }
    public string? States { get; set; }
    public string? StatesTags { get; set; }
    public string? StatesEn { get; set; }
    public string? BrandOwner { get; set; }
    public string? EnvironmentalScoreScore { get; set; }
    public string? EnvironmentalScoreGrade { get; set; }
    public string? NutrientLevelsTags { get; set; }
    public string? ProductQuantity { get; set; }
    public string? Owner { get; set; }
    public string? DataQualityErrorsTags { get; set; }
    public string? UniqueScansN { get; set; }
    public string? PopularityTags { get; set; }
    public string? Completeness { get; set; }
    public string? LastImageT { get; set; }
    public string? LastImageDatetime { get; set; }
    public string? MainCategory { get; set; }
    public string? MainCategoryEn { get; set; }
    public string? ImageUrl { get; set; }
    public string? ImageSmallUrl { get; set; }
    public string? ImageIngredientsUrl { get; set; }
    public string? ImageIngredientsSmallUrl { get; set; }
    public string? ImageNutritionUrl { get; set; }
    public string? ImageNutritionSmallUrl { get; set; }
    public string? EnergyKj100g { get; set; }
    public string? EnergyKcal100g { get; set; }
    public string? Energy100g { get; set; }
    public string? EnergyFromFat100g { get; set; }
    public string? Fat100g { get; set; }
    public string? SaturatedFat100g { get; set; }
    public string? ButyricAcid100g { get; set; }
    public string? CaproicAcid100g { get; set; }
    public string? CaprylicAcid100g { get; set; }
    public string? CapricAcid100g { get; set; }
    public string? LauricAcid100g { get; set; }
    public string? MyristicAcid100g { get; set; }
    public string? PalmiticAcid100g { get; set; }
    public string? StearicAcid100g { get; set; }
    public string? ArachidicAcid100g { get; set; }
    public string? BehenicAcid100g { get; set; }
    public string? LignocericAcid100g { get; set; }
    public string? CeroticAcid100g { get; set; }
    public string? MontanicAcid100g { get; set; }
    public string? MelissicAcid100g { get; set; }
    public string? UnsaturatedFat100g { get; set; }
    public string? MonounsaturatedFat100g { get; set; }
    public string? Omega9Fat100g { get; set; }
    public string? PolyunsaturatedFat100g { get; set; }
    public string? Omega3Fat100g { get; set; }
    public string? Omega6Fat100g { get; set; }
    public string? AlphaLinolenicAcid100g { get; set; }
    public string? EicosapentaenoicAcid100g { get; set; }
    public string? DocosahexaenoicAcid100g { get; set; }
    public string? LinoleicAcid100g { get; set; }
    public string? ArachidonicAcid100g { get; set; }
    public string? GammaLinolenicAcid100g { get; set; }
    public string? DihomoGammaLinolenicAcid100g { get; set; }
    public string? OleicAcid100g { get; set; }
    public string? ElaidicAcid100g { get; set; }
    public string? GondoicAcid100g { get; set; }
    public string? MeadAcid100g { get; set; }
    public string? ErucicAcid100g { get; set; }
    public string? NervonicAcid100g { get; set; }
    public string? TransFat100g { get; set; }
    public string? Cholesterol100g { get; set; }
    public string? Carbohydrates100g { get; set; }
    public string? Sugars100g { get; set; }
    public string? AddedSugars100g { get; set; }
    public string? Sucrose100g { get; set; }
    public string? Glucose100g { get; set; }
    public string? Fructose100g { get; set; }
    public string? Galactose100g { get; set; }
    public string? Lactose100g { get; set; }
    public string? Maltose100g { get; set; }
    public string? Maltodextrins100g { get; set; }
    public string? Psicose100g { get; set; }
    public string? Starch100g { get; set; }
    public string? Polyols100g { get; set; }
    public string? Erythritol100g { get; set; }
    public string? Isomalt100g { get; set; }
    public string? Maltitol100g { get; set; }
    public string? Sorbitol100g { get; set; }
    public string? Fiber100g { get; set; }
    public string? SolubleFiber100g { get; set; }
    public string? Polydextrose100g { get; set; }
    public string? InsolubleFiber100g { get; set; }
    public string? Proteins100g { get; set; }
    public string? Casein100g { get; set; }
    public string? SerumProteins100g { get; set; }
    public string? Nucleotides100g { get; set; }
    public string? Salt100g { get; set; }
    public string? AddedSalt100g { get; set; }
    public string? Sodium100g { get; set; }
    public string? Alcohol100g { get; set; }
    public string? VitaminA100g { get; set; }
    public string? BetaCarotene100g { get; set; }
    public string? VitaminD100g { get; set; }
    public string? VitaminE100g { get; set; }
    public string? VitaminK100g { get; set; }
    public string? VitaminC100g { get; set; }
    public string? VitaminB1100g { get; set; }
    public string? VitaminB2100g { get; set; }
    public string? VitaminPp100g { get; set; }
    public string? VitaminB6100g { get; set; }
    public string? VitaminB9100g { get; set; }
    public string? Folates100g { get; set; }
    public string? VitaminB12100g { get; set; }
    public string? Biotin100g { get; set; }
    public string? PantothenicAcid100g { get; set; }
    public string? Silica100g { get; set; }
    public string? Bicarbonate100g { get; set; }
    public string? Potassium100g { get; set; }
    public string? Chloride100g { get; set; }
    public string? Calcium100g { get; set; }
    public string? Phosphorus100g { get; set; }
    public string? Iron100g { get; set; }
    public string? Magnesium100g { get; set; }
    public string? Zinc100g { get; set; }
    public string? Copper100g { get; set; }
    public string? Manganese100g { get; set; }
    public string? Fluoride100g { get; set; }
    public string? Selenium100g { get; set; }
    public string? Chromium100g { get; set; }
    public string? Molybdenum100g { get; set; }
    public string? Iodine100g { get; set; }
    public string? Caffeine100g { get; set; }
    public string? Taurine100g { get; set; }
    public string? Methylsulfonylmethane100g { get; set; }
    public string? Hydroxymethylbutyrate100g { get; set; }
    public string? Ph100g { get; set; }
    public string? FruitsVegetablesLegumes100g { get; set; }
    public string? CollagenMeatProteinRatio100g { get; set; }
    public string? Cocoa100g { get; set; }
    public string? Chlorophyl100g { get; set; }
    public string? CarbonFootprint100g { get; set; }
    public string? GlycemicIndex100g { get; set; }
    public string? WaterHardness100g { get; set; }
    public string? Choline100g { get; set; }
    public string? Phylloquinone100g { get; set; }
    public string? BetaGlucan100g { get; set; }
    public string? Inositol100g { get; set; }
    public string? Carnitine100g { get; set; }
    public string? Sulphate100g { get; set; }
    public string? Nitrate100g { get; set; }
    public string? Acidity100g { get; set; }
    public string? CarbohydratesTotal100g { get; set; }
    public string? Water100g { get; set; }
}